### ISSUE TITLE
findlib.sh missing

### ISSUE THREAD

**Issue by fractilegames** [desura/Desurium#370] opened 2012-12-07 10:37 UTC
In Linux the Desura client installs libraries markes as dependencies for game even if those already exists in system. I have verified this in Debian Squeeze  and Xubuntu 12.10 and with both Desura and Desurium built from git master today. Only tested with my own game (The Platform Shooter), which has  libGLU and libXaw set as dependencies.

After building Desurium in Xubuntu 12.10 and installing only this one game from there the libraries can be found in these locations:

/home/mikko/.desura/games/14729/3496/lib/libXaw.so.7
/home/mikko/.desura/tools/202/libXaw.so.7
/usr/lib/i386-linux-gnu/libXaw.so.7
/usr/lib/x86_64-linux-gnu/libXaw.so.7

/home/mikko/.desura/games/14729/3496/lib/libGLU.so.1
/home/mikko/.desura/tools/95/libGLU.so.1
/usr/lib/i386-linux-gnu/libGLU.so.1
/usr/lib/i386-linux-gnu/libGLU.so.1.3.1
/usr/lib/x86_64-linux-gnu/libGLU.so.1
/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1

This is a major problem for my game, because the libXaw.so.7 library installed by Desura is incompatible with all Debian versions (and many distributions based on them). See forum post here: http://www.desura.com/groups/desura/forum/thread/problems-with-libxawso7-installed-by-desura

EDIT (karolherbst):
we need the findlib.sh shell script for this

**Comment by Jookia** [comment] 2012-12-07 11:01
Maybe we should set LD_LIBRARY_PATH to have Desurium libraries last?

**Comment by fractilegames** [comment] 2012-12-07 11:28
Anything in LD_LIBRARY_PATH is searched before the system directories. To have system directories searched before Desurium library directory, the system directories would have to be added in LD_LIBRARY_PATH, which does not sound like a good idea..

**Comment by karolherbst** [comment] 2012-12-07 12:23
duplicate of #326, but I will close mine, because there is not so much content

**Comment by karolherbst** [comment] 2012-12-07 12:31
but yes, we could modify https://github.com/lodle/Desurium/blob/master/build_out/run.sh and test this. And because everybody can modify this file without harming or recompiling desurium we can test this approach

```
if [[ "@RUNTIME_LIB_INSOURCE_DIR@" = /* ]]; then
    LD_LIBRARY_PATH="@RUNTIME_LIB_INSOURCE_DIR@/" @RUNTIME_LIB_INSOURCE_DIR@/desura $@
else
    LD_LIBRARY_PATH="$DIR/@RUNTIME_LIB_INSOURCE_DIR@/" $DIR/@RUNTIME_LIB_INSOURCE_DIR@/desura $@
fi
```

=>

```
SYSTEM_LIBRARY_PATH="/lib64/;/lib32/;/usr/lib64/;/usr/lib32/"
if [[ "@RUNTIME_LIB_INSOURCE_DIR@" = /* ]]; then
    LD_LIBRARY_PATH="${SYSTEM_LIBRARY_PATH};@RUNTIME_LIB_INSOURCE_DIR@/" @RUNTIME_LIB_INSOURCE_DIR@/desura $@
else
    LD_LIBRARY_PATH="${SYSTEM_LIBRARY_PATH};$DIR/@RUNTIME_LIB_INSOURCE_DIR@/" $DIR/@RUNTIME_LIB_INSOURCE_DIR@/desura $@
fi
```

of course @RUNTIME_LIB_INSOURCE_DIR@ is replaced in the binary versions, but I don't like this approach, too.

I don't know how the handling with 32bit libs is on a 64bit system while launching a 32bit games. the 64bit libs could be existing, but not the 32bit ones.

I would like to have a dependency system with calls to the package manager itself. We have to translate some names then, but this should not be the problem.

**Comment by fractilegames** [comment] 2012-12-08 14:57
I tried editing the start script as suggested, only with paths like this:
SYSTEM_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu"

It didn't help. However, manually running this in game directory does work:
LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu" ./desura_launch_Play.sh 

One problem with this approach is that required system library paths might vary between distributions.

**Comment by karolherbst** [comment] 2013-01-24 18:40
desura uses a shell script called findlib.sh for this

**Comment by Jookia** [comment] 2013-01-24 18:45
Are we looking for the findlib.sh script from the prebuilt CEF days?

**Comment by karolherbst** [comment] 2013-01-25 08:30
correctly

**Closed as completed** 2013-01-29 08:08 UTC
Labels: bug, build-system
