### ISSUE TITLE
cef compiles with several jobs altough not specified.

### ISSUE THREAD

**Issue by matthiaskrgr** [desura/Desurium#473] opened 2013-02-12 22:35 UTC
Heading already says it.

Cef compilation should not run multiple jobs until we explicitly say so.

**Comment by matthiaskrgr** [comment] 2013-02-12 22:42
passing -j 1 doesn't seem to have any effects

**Comment by karolherbst** [comment] 2013-02-13 06:59
Duplicate of #415

**Closed as completed** 2013-02-13 06:59 UTC
