### ISSUE TITLE
Locally-installed entries are forced to "Not Installed" on restart

### ISSUE THREAD

**Issue by ssokolow** [desura/Desurium#223] opened 2012-05-21 01:26 UTC
When I switched from the latest non-GPL Desura (Linux version) to revision 3a317cf5201efb96469434b4f320971ae256c544, all of my locally-installed games were marked as "Not Installed".

In the process of trying to compare an identical "Installed" and "Not Installed" entry, I discovered that, while an "Installed" entry can be created (In my case, for `/usr/games/frogatto`) and will execute properly, it will reset to "Not Installed" when Desura is restarted. (cleanly or via killall and `SIGTERM` as I use when the non-GPL version won't exit)

I've also confirmed that the contents of `iteminfo_d.sqlite` for newly-created entries are identical to the old ones migrated over. (I deleted and re-created the one for `/usr/games/frogatto` and only the primary key changed)

**Comment by r-ick** [comment] 2012-08-12 15:35
I've had the same problem here, tracked it down to a primary key conflict over the branch ID. The above fixes it for me, does it work for anyone else? Does anyone mind if I post a pull request?

**Comment by karolherbst** [comment] 2012-08-13 21:28
the problem is, that the desura files are stored in ~/.desura

it is possible to reference to system-wide installed games, but it would be cleaner to make a whole client migration from non-GPL to GPL client

**Comment by r-ick** [comment] 2012-08-14 09:08
If you mean "do a completely clean GPL install", the bug is still there even after deleting ~/.desura and starting from scratch.

Add 2 or more local entries, restart, only one remains "Installed". The problem is that they are all assigned the same fixed BranchInfo branchid of 0. That being the primary key, if nothing else has claimed it, only one is successfully written to the table. The rest, it seems, fail silently.

I confess I can't see how the non-GPL client could have done it, but what I've committed above works for me without issue.

**Comment by karolherbst** [comment] 2012-08-14 09:15
okay, if it is working, you should create a pull request, so it can be reviewed by other developers and users

**Closed as completed** 2012-09-16 15:13 UTC
Labels: bug
