### ISSUE TITLE
Feature Request: Fully Free Software Server for Desurium

### ISSUE THREAD

**Issue by g4jc** [desura/Desurium#495] opened 2013-02-23 17:36 UTC
First off I think this is an excellent project, a fully GPL client to manage games. The only downside is it cannot be packaged in FSF approved  distros because the download server contains games which are non-free. For a list of distros affected see: https://www.gnu.org/distros/free-distros.html

I think it would be an excellent edition to provide a server for the Desurium client that includes only-free games. Or a simple and effective way of filtering the games to show only fully-free games by default.

Then users could install fully free software on their GNU/Linux distros. Many games meet this criteria, here are just a few:
- Strategy: 0AD, MegaGlest, The Battle for Wesnoth, Hedgewars, Wormux
- Racing: TORCS, SuperTuxKart, Rigs of Rods
  etc.
  We would also be finding some libre game jewels along the way. I'm sure there's more we haven't found yet, and a repository like this would be invaluable. :D

**Comment by makson96** [comment] 2013-02-23 19:25
My few notes about this:
1. There are already many opensource games distributed via Desura. Wesnoth, Warsow, OpenArena, Xonotic and many, many more. Nobody prohibits putting opensource games on Desura Server.
2. There seems to be no point in making new software for distributing only opensource games, because there will be no difference between it and standard package manager.
3. One interesting thing for this project might be to segregate games by licenses (commercial, free, opensource).

**Comment by g4jc** [comment] 2013-02-23 21:06
I think segregating by license is probably the way to go too, though there would have to be an option to only show libre games by default for it to be included in said distros.

**Comment by karolherbst** [comment] 2013-02-23 22:17
duplicate of #309

**Closed as completed by karolherbst** 2013-02-23 22:17 UTC

**Comment by onpon4** [comment] 2013-03-30 01:28
#309 seems to be missing...

**Comment by karolherbst** [comment] 2013-03-30 10:43
mhhh, strange.
