### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by matthiaskrgr** [desura/Desurium#270] opened 2012-07-19 07:32 UTC
```
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:154:5: note: template<class Source> boost::filesystem::path::path(const Source&, const codecvt_type&)
/usr/include/boost/filesystem/path.hpp:154:5: note:   template argument deduction/substitution failed:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:413:83: note:   candidate expects 2 arguments, 1 provided
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:151:5: note: boost::filesystem::path::path(const std::basic_string<char>&)
/usr/include/boost/filesystem/path.hpp:151:5: note:   no known conversion for argument 1 from ‘gcWString {aka gcBaseString<wchar_t>}’ to ‘const std::basic_string<char>&’
/usr/include/boost/filesystem/path.hpp:150:5: note: boost::filesystem::path::path(const value_type*)
/usr/include/boost/filesystem/path.hpp:150:5: note:   no known conversion for argument 1 from ‘gcWString {aka gcBaseString<wchar_t>}’ to ‘const value_type* {aka const char*}’
/usr/include/boost/filesystem/path.hpp:135:5: note: template<class Source> boost::filesystem::path::path(const Source&, typename boost::enable_if<boost::filesystem::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*)
/usr/include/boost/filesystem/path.hpp:135:5: note:   template argument deduction/substitution failed:
/usr/include/boost/filesystem/path.hpp: In substitution of ‘template<class Source> boost::filesystem::path::path(const Source&, typename boost::enable_if<boost::filesystem::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*) [with Source = gcBaseString<wchar_t>]’:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:413:83:   required from here
/usr/include/boost/filesystem/path.hpp:135:5: error: no type named ‘type’ in ‘struct boost::enable_if<boost::filesystem::path_traits::is_pathable<gcBaseString<wchar_t> >, void>’
/usr/include/boost/filesystem/path.hpp:132:5: note: boost::filesystem::path::path(const boost::filesystem::path&)
/usr/include/boost/filesystem/path.hpp:132:5: note:   no known conversion for argument 1 from ‘gcWString {aka gcBaseString<wchar_t>}’ to ‘const boost::filesystem::path&’
/usr/include/boost/filesystem/path.hpp:130:5: note: boost::filesystem::path::path()
/usr/include/boost/filesystem/path.hpp:130:5: note:   candidate expects 0 arguments, 1 provided
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp: In function ‘void UTIL::FS::getAllFiles(UTIL::FS::Path, std::vector<UTIL::FS::Path>&, std::vector<std::basic_string<char> >*)’:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:418:65: error: no matching function for call to ‘boost::filesystem::path::path(gcWString, bool (&)(const string&))’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:418:65: note: candidates are:
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:172:5: note: template<class InputIterator> boost::filesystem::path::path(InputIterator, InputIterator, const codecvt_type&)
/usr/include/boost/filesystem/path.hpp:172:5: note:   template argument deduction/substitution failed:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:418:65: note:   deduced conflicting types for parameter ‘InputIterator’ (‘gcBaseString<wchar_t>’ and ‘bool (*)(const string&) {aka bool (*)(const std::basic_string<char>&)}’)
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:161:5: note: template<class InputIterator> boost::filesystem::path::path(InputIterator, InputIterator)
/usr/include/boost/filesystem/path.hpp:161:5: note:   template argument deduction/substitution failed:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:418:65: note:   deduced conflicting types for parameter ‘InputIterator’ (‘gcBaseString<wchar_t>’ and ‘bool (*)(const string&) {aka bool (*)(const std::basic_string<char>&)}’)
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:154:5: note: template<class Source> boost::filesystem::path::path(const Source&, const codecvt_type&)
/usr/include/boost/filesystem/path.hpp:154:5: note:   template argument deduction/substitution failed:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:418:65: note:   cannot convert ‘boost::filesystem::native’ (type ‘bool(const string&) {aka bool(const std::basic_string<char>&)}’) to type ‘const codecvt_type& {aka const std::codecvt<wchar_t, char, __mbstate_t>&}’
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:151:5: note: boost::filesystem::path::path(const std::basic_string<char>&)
/usr/include/boost/filesystem/path.hpp:151:5: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/filesystem/path.hpp:150:5: note: boost::filesystem::path::path(const value_type*)
/usr/include/boost/filesystem/path.hpp:150:5: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/filesystem/path.hpp:135:5: note: template<class Source> boost::filesystem::path::path(const Source&, typename boost::enable_if<boost::filesystem::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*)
/usr/include/boost/filesystem/path.hpp:135:5: note:   template argument deduction/substitution failed:
/usr/include/boost/filesystem/path.hpp: In substitution of ‘template<class Source> boost::filesystem::path::path(const Source&, typename boost::enable_if<boost::filesystem::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*) [with Source = gcBaseString<wchar_t>]’:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:418:65:   required from here
/usr/include/boost/filesystem/path.hpp:135:5: error: no type named ‘type’ in ‘struct boost::enable_if<boost::filesystem::path_traits::is_pathable<gcBaseString<wchar_t> >, void>’
/usr/include/boost/filesystem/path.hpp:132:5: note: boost::filesystem::path::path(const boost::filesystem::path&)
/usr/include/boost/filesystem/path.hpp:132:5: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/filesystem/path.hpp:130:5: note: boost::filesystem::path::path()
/usr/include/boost/filesystem/path.hpp:130:5: note:   candidate expects 0 arguments, 2 provided
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:423:2: error: ‘wdirectory_iterator’ is not a member of ‘bf’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:423:26: error: expected ‘;’ before ‘end_iter’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:424:7: error: ‘wdirectory_iterator’ is not a member of ‘bf’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:424:31: error: expected ‘;’ before ‘dirIt’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:424:49: error: ‘dirIt’ was not declared in this scope
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:424:56: error: ‘end_iter’ was not declared in this scope
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp: In function ‘void UTIL::FS::getAllFolders(UTIL::FS::Path, std::vector<UTIL::FS::Path>&)’:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:453:65: error: no matching function for call to ‘boost::filesystem::path::path(gcWString, bool (&)(const string&))’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:453:65: note: candidates are:
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:172:5: note: template<class InputIterator> boost::filesystem::path::path(InputIterator, InputIterator, const codecvt_type&)
/usr/include/boost/filesystem/path.hpp:172:5: note:   template argument deduction/substitution failed:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:453:65: note:   deduced conflicting types for parameter ‘InputIterator’ (‘gcBaseString<wchar_t>’ and ‘bool (*)(const string&) {aka bool (*)(const std::basic_string<char>&)}’)
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:161:5: note: template<class InputIterator> boost::filesystem::path::path(InputIterator, InputIterator)
/usr/include/boost/filesystem/path.hpp:161:5: note:   template argument deduction/substitution failed:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:453:65: note:   deduced conflicting types for parameter ‘InputIterator’ (‘gcBaseString<wchar_t>’ and ‘bool (*)(const string&) {aka bool (*)(const std::basic_string<char>&)}’)
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:154:5: note: template<class Source> boost::filesystem::path::path(const Source&, const codecvt_type&)
/usr/include/boost/filesystem/path.hpp:154:5: note:   template argument deduction/substitution failed:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:453:65: note:   cannot convert ‘boost::filesystem::native’ (type ‘bool(const string&) {aka bool(const std::basic_string<char>&)}’) to type ‘const codecvt_type& {aka const std::codecvt<wchar_t, char, __mbstate_t>&}’
In file included from /usr/include/boost/filesystem.hpp:16:0,
                 from /home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:24:
/usr/include/boost/filesystem/path.hpp:151:5: note: boost::filesystem::path::path(const std::basic_string<char>&)
/usr/include/boost/filesystem/path.hpp:151:5: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/filesystem/path.hpp:150:5: note: boost::filesystem::path::path(const value_type*)
/usr/include/boost/filesystem/path.hpp:150:5: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/filesystem/path.hpp:135:5: note: template<class Source> boost::filesystem::path::path(const Source&, typename boost::enable_if<boost::filesystem::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*)
/usr/include/boost/filesystem/path.hpp:135:5: note:   template argument deduction/substitution failed:
/usr/include/boost/filesystem/path.hpp: In substitution of ‘template<class Source> boost::filesystem::path::path(const Source&, typename boost::enable_if<boost::filesystem::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*) [with Source = gcBaseString<wchar_t>]’:
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:453:65:   required from here
/usr/include/boost/filesystem/path.hpp:135:5: error: no type named ‘type’ in ‘struct boost::enable_if<boost::filesystem::path_traits::is_pathable<gcBaseString<wchar_t> >, void>’
/usr/include/boost/filesystem/path.hpp:132:5: note: boost::filesystem::path::path(const boost::filesystem::path&)
/usr/include/boost/filesystem/path.hpp:132:5: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/filesystem/path.hpp:130:5: note: boost::filesystem::path::path()
/usr/include/boost/filesystem/path.hpp:130:5: note:   candidate expects 0 arguments, 2 provided
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:458:2: error: ‘wdirectory_iterator’ is not a member of ‘bf’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:458:26: error: expected ‘;’ before ‘end_iter’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:459:7: error: ‘wdirectory_iterator’ is not a member of ‘bf’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:459:31: error: expected ‘;’ before ‘dirIt’
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:459:49: error: ‘dirIt’ was not declared in this scope
/home/matthias/vcs/github/desurium_fork_bkp/src/static/util_fs/code/UtilFs.cpp:459:56: error: ‘end_iter’ was not declared in this scope
make[2]: *** [src/static/util_fs/CMakeFiles/util_fs.dir/code/UtilFs.cpp.o] Error 1
make[1]: *** [src/static/util_fs/CMakeFiles/util_fs.dir/all] Error 2
make: *** [all] Error 2
```

arch linux,
boost 1.50.0-1
glibc  2.16.0-2

**Comment by makson96** [comment] 2012-07-19 07:44
The same bug as Issue #261

Maybe try branch boost_fs3.

**Comment by karolherbst** [comment] 2012-07-19 08:42
ahh yeah, I didn't see that matthiaskrgr tried to build master. Please try the boost_fs3 branch, there all these issues should be fixed

**Comment by karolherbst** [comment] 2012-07-19 11:43
not a bug

**Closed as completed by karolherbst** 2012-07-19 11:43 UTC
