### ISSUE TITLE
Adding support for libindicator for Ubuntu

### ISSUE THREAD

**Issue by Giako** [desura/Desurium#534] opened 2013-04-03 19:04 UTC
In the next releases, the Ubuntu development team is planning to ditch traybar icons (such as Desurium tray icon), except for Wine and Java applications, which are unaware of the OS on which they're running.

Currently tray icons are rendered in Unity only on the main screen in a multi-screen environment (this is Ubuntu's fault, but I don't think they'll fix this issue).

It'd be fantastic to add a Desurium indicator, similarly to the Steam for Linux one. What do you think?

**Comment by karolherbst** [comment] 2013-04-03 20:40
duplicate of #65 ?

**Comment by Giako** [comment] 2013-04-03 20:45
It seems so :) I didn't find any similar issue on the search bar... but it seems I'm wrong. You can mark this as duplicate.

**Closed as completed** 2013-04-03 22:30 UTC
